serial:
  port: COM2

files:
  mwt_storage: mwt_storage.csv
  mwt_constants: mwt_constants.yaml
  error_log: mwt_error_log.txt
  event_log: mwt_event_log.txt

ui:
  # options: system | light | dark
  appearance: system

  # options: blue | green | dark-blue | sweetkind
  color: blue

